#!/usr/bin/perl

if ($ARGV[0] =~ m/(\d+)/) {
	$multiplier = $1;
} else {
	print "Error input pararmeter\nUsage: dimen_multiply.pl MULTIPLIER SOURCE_FILE > TARGET_FILE\n";
	exit 0;
}

open(INPUT_FILE, $ARGV[1]);
while(<INPUT_FILE>) {
	chomp;
	my $line = $_;
	if (($head, $sign, $dimen, $unit, $tail) = $line =~ m/(\s*<dimen name="\S+">)([\+-]*)(\d+)(\S+)(<\/dimen>)/) {
		$new_dimen = ($unit eq 'px') ? int($dimen / $multiplier) : $dimen;
		print "$head$sign$new_dimen$unit$tail\n";
	} else {
		print "$line\n";
	}
}
